version: "3.9"
services:
  db_service:
    image: postgres:latest
    container_name: migow-postgres-db
    hostname: localhost
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: migow
    volumes:
      - db_service-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin_service:
    image: dpage/pgadmin4
    container_name: migow-pgadmin
    depends_on:
      - db_service
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_service-data:/var/lib/pgadmin
    restart: unless-stopped
volumes:
  db_service-data:
  pgadmin_service-data:
        
    